name: Kestrel
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
pygments: true
permalink: /:year/:month/:day/:title
baseurl: /kestrel

