#ifndef E_SDCARD_H
#define E_SDCARD_H


#define GPIA_OUT_SD_LED		0x0001
#define GPIA_OUT_SD_SS		0x0002
#define GPIA_OUT_SD_MOSI	0x0004
#define GPIA_OUT_SD_CLK		0x0008

#define GPIA_IN_SD_CD		0x0001
#define GPIA_IN_SD_WP		0x0002
#define GPIA_IN_SD_MISO		0x0004


extern UDWORD gpia_out;
extern UDWORD gpia_in;


#define SDCMD_BASE		0x40
#define	SDCMD_GO_IDLE_STATE	SDCMD_BASE
#define SDCMD_SEND_OP_COND	SDCMD_BASE+1
#define SDCMD_SEND_IF_COND	SDCMD_BASE+8
#define SDCMD_SEND_CSD		SDCMD_BASE+9
#define SDCMD_SEND_CID		SDCMD_BASE+10
#define SDCMD_STOP_TRANSMISSION	SDCMD_BASE+12
#define SDCMD_SET_BLKLEN	SDCMD_BASE+16
#define SDCMD_READ_BLOCK	SDCMD_BASE+17
#define SDCMD_READ_MULTIPLE	SDCMD_BASE+18
#define SDCMD_SET_BLK_COUNT	SDCMD_BASE+23
#define SDCMD_WRITE_BLOCK	SDCMD_BASE+24
#define SDCMD_WRITE_MULTIPLE	SDCMD_BASE+25
#define SDCMD_APP_CMD		SDCMD_BASE+55
#define SDCMD_READ_OCR		SDCMD_BASE+58


void handle_spi(void);


#endif

